# Generated by Django 3.1 on 2020-08-28 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0002_organization_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='associates',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='conferences',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='public',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='associate',
            name='event_id',
            field=models.ManyToManyField(db_table='event_associate', related_name='event_associates', to='api_rest.Event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='organization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_event', to='api_rest.organization'),
        ),
        migrations.AlterField(
            model_name='event',
            name='user_id',
            field=models.ManyToManyField(db_table='user_event', related_name='user_event', to='api_rest.UserE'),
        ),
        migrations.AlterField(
            model_name='eventdata',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_data', to='api_rest.event'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_event', to='api_rest.event'),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='schedule_id',
            field=models.ManyToManyField(db_table='shedule_speaker', related_name='schedule_speaker', to='api_rest.Schedule'),
        ),
    ]
