# Generated by Django 3.1 on 2020-08-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0003_auto_20200828_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='user_id',
            field=models.ManyToManyField(db_table='user_event', related_name='user_event_relation', to='api_rest.UserE'),
        ),
    ]
