# Generated by Django 3.1 on 2020-08-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0006_auto_20200829_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='url',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='organization',
            name='url',
            field=models.CharField(max_length=255),
        ),
    ]
