# Generated by Django 3.1 on 2020-08-29 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0007_auto_20200829_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usere',
            name='email',
            field=models.CharField(max_length=150),
        ),
    ]
