# Generated by Django 3.1 on 2020-08-30 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0010_auto_20200829_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_start_date',
            field=models.CharField(max_length=100),
        ),
    ]
